@extends('layouts.main', ['lang' => 'tr'])

@section('title', 'Tedarikçi Yetkilisinin Sözleşme Süreçleri Metni - Port Nature Luxury Resort Hotel Spa')
@section('description', 'KVKK Port Nature Luxury Resort Hotel Spa. Denize sıfır en iyi 10 aile dostu Antalya oteli. Tek tıkla her şey dahil tatil rezervasyonu yapın.')


@section('content')
<div class="d-flex  justify-content-center align-items-start" style="margin-top:100px;min-height: calc(100vh - 515px);">

    <div class="container mt-5 px-5">
        <!-- Nav tabs -->
        <div id="tab-8" class="tab-content">
            <div class="WordSection1">
                <p class="MsoNormal" style="margin-bottom:4.0pt;"><span style="font-size:18.0pt; line-height:107%;color:#002060;">Kişisel Verilerin Korunması</span></p>
                <h1>Tedarik&ccedil;i Yetkilisinin S&ouml;zleşme S&uuml;re&ccedil;lerinde İşlenen Kişisel Verilerine İlişkin Aydınlatma Metni</h1>
                <p class="MsoNormal" style="margin-bottom:7.8pt;">&nbsp;</p>
                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:9.05pt; margin-left:-.25pt;text-align:justify;text-justify:inter-ideograph;text-indent: -.5pt;line-height:112%;"><span style='font-family:"Times New Roman",serif; color:#002060;'>6698 sayılı Kişisel Verilerin Korunması Kanunu&apos;na (&ldquo;Kanun&rdquo;) g&ouml;re</span> <strong><span style='font-size:10.5pt;line-height:112%;font-family:"Times New Roman",serif; color:#002060;'>ARAS İNŞAAT TİCARET TURİZM ANONİM ŞİRKETİ</span></strong> <span style='font-family:"Times New Roman",serif;color:#002060;'>(&ldquo;Bundan sonra &lsquo;</span><strong><span style='font-size:10.5pt;line-height:112%;font-family:"Times New Roman",serif; color:#002060;'>PORT NATURE</span></strong><strong><span style='font-family:"Times New Roman",serif; color:#002060;'>&rsquo;</span></strong> <span style='font-family:"Times New Roman",serif; color:#002060;'>olarak anılacaktır.&rdquo;) sizinle ilgili kişisel verileri işlemesi sebebiyle veri sorumlusu olarak tanımlanmaktadır. Kanunun &quot;Aydınlatma Y&uuml;k&uuml;ml&uuml;l&uuml;ğ&uuml;&quot; başlıklı 10&rsquo;uncu maddesine g&ouml;re veri sorumluları, kişisel verilerini işledikleri ger&ccedil;ek kişileri bazı konularda bilgilendirmekle y&uuml;k&uuml;ml&uuml;d&uuml;r.</span></p>
                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:11.5pt; margin-left:-.25pt;text-align:justify;text-justify:inter-ideograph;text-indent: -.5pt;line-height:107%;"><span style='font-family:"Times New Roman",serif; color:#002060;'>Bu metin hem mevzuata uyum sağlanması hem de şeffaf ve hesap verebilir olabilmek amacıyla</span> <strong><span style='font-size:10.5pt; line-height:107%;font-family:"Times New Roman",serif;color:#002060;'>PORT NATURE</span></strong> <span style='font-family:"Times New Roman",serif;color:#002060;'>tarafından hazırlanmıştır.</span></p>
                <p class="MsoNormal" style="margin-bottom:9.9pt;"><strong><span style='font-size:12.0pt; line-height:107%;font-family:"Times New Roman",serif;color:#002060;'>Tanımlar</span></strong></p>
                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:9.95pt; margin-left:-.25pt;text-align:justify;text-justify:inter-ideograph;text-indent: -.5pt;line-height:109%;"><span style='font-size:12.0pt;line-height:109%; font-family:"Times New Roman",serif;color:#002060;'>6698 sayılı Kişisel Verilerin Korunması Kanunu&apos;na g&ouml;re:</span></p>
                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:9.95pt; margin-left:-.25pt;text-align:justify;text-justify:inter-ideograph;text-indent: -.5pt;line-height:109%;"><strong><span style='font-size:12.0pt;line-height:109%; font-family:"Times New Roman",serif;color:#002060;'>Kişisel veri</span></strong><span style='font-size:12.0pt;line-height:109%;font-family:"Times New Roman",serif; color:#002060;'>, kimliği belirli veya belirlenebilir ger&ccedil;ek kişiye ilişkin her t&uuml;rl&uuml; bilgiyi;</span></p>
                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:7.85pt; margin-left:-.25pt;text-align:justify;text-justify:inter-ideograph;text-indent: -.5pt;line-height:109%;"><strong><span style='font-size:12.0pt;line-height:109%; font-family:"Times New Roman",serif;color:#002060;'>&Ouml;zel Nitelikli Kişisel Veri:</span></strong> <span style='font-size:12.0pt;line-height:109%;font-family:"Times New Roman",serif; color:#002060;'>Kişilerin ırkı, etnik k&ouml;keni, siyasi d&uuml;ş&uuml;ncesi, felsefi inancı, dini, mezhebi veya diğer inan&ccedil;ları, kılık ve kıyafeti, dernek, vakıf ya da sendika &uuml;yeliği, sağlığı, cinsel hayatı, ceza mahk&ucirc;miyeti ve g&uuml;venlik tedbirleriyle ilgili verileri ile biyometrik ve genetik verileri,</span></p>
                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:9.95pt; margin-left:-.25pt;text-align:justify;text-justify:inter-ideograph;text-indent: -.5pt;line-height:109%;"><strong><span style='font-size:12.0pt;line-height:109%; font-family:"Times New Roman",serif;color:#002060;'>Kişisel verilerin işlenmesi</span></strong><span style='font-size:12.0pt;line-height:109%;font-family:"Times New Roman",serif; color:#002060;'>, kişisel verilerin tamamen veya kısmen otomatik olan ya da herhangi bir veri kayıt sisteminin par&ccedil;ası olmak kaydıyla otomatik olmayan yollarla elde edilmesi, kaydedilmesi, depolanması, muhafaza edilmesi, değiştirilmesi, yeniden d&uuml;zenlenmesi, a&ccedil;ıklanması, aktarılması, devralınması, elde edilebilir h&acirc;le getirilmesi, sınıflandırılması ya da kullanılmasının engellenmesi gibi veriler &uuml;zerinde ger&ccedil;ekleştirilen her t&uuml;rl&uuml; işlemi;</span></p>
                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:9.95pt; margin-left:-.25pt;text-align:justify;text-justify:inter-ideograph;text-indent: -.5pt;line-height:109%;"><strong><span style='font-size:12.0pt;line-height:109%; font-family:"Times New Roman",serif;color:#002060;'>İlgili kişi</span></strong><span style='font-size:12.0pt;line-height:109%;font-family:"Times New Roman",serif; color:#002060;'>, kişisel verisi işlenen ger&ccedil;ek kişiyi;</span></p>
                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:7.5pt; margin-left:-.25pt;text-align:justify;text-justify:inter-ideograph;text-indent: -.5pt;line-height:109%;"><strong><span style='font-size:12.0pt;line-height:109%; font-family:"Times New Roman",serif;color:#002060;'>Veri sorumlusu</span></strong><span style='font-size:12.0pt;line-height:109%;font-family:"Times New Roman",serif; color:#002060;'>, kişisel verilerin işleme ama&ccedil;larını ve vasıtalarını belirleyen, veri kayıt sisteminin kurulmasından ve y&ouml;netilmesinden sorumlu olan ger&ccedil;ek veya t&uuml;zel kişiyi</span></p>
                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:6.9pt; margin-left:-.25pt;text-align:justify;text-justify:inter-ideograph;text-indent: -.5pt;line-height:109%;"><strong><span style='font-size:12.0pt;line-height:109%; font-family:"Times New Roman",serif;color:#002060;'>Aydınlatma y&uuml;k&uuml;ml&uuml;l&uuml;ğ&uuml;</span></strong><span style='font-size:12.0pt;line-height:109%;font-family:"Times New Roman",serif; color:#002060;'>, kişisel verilerin elde edilmesi sırasında veri sorumlusu veya yetkilendirdiği kişinin, ilgili kişilere; veri sorumlusunun kimliği, kişisel verilerin hangi ama&ccedil;la işleneceği, işlenen kişisel verilerin kimlere ve hangi ama&ccedil;la aktarılabileceği, kişisel veri toplama y&ouml;ntemi ve hukuki sebebi ve Kanun&apos;un 11&apos;inci maddesinde sayılan diğer hakları konusunda bilgi verme y&uuml;k&uuml;ml&uuml;l&uuml;ğ&uuml;n&uuml;; ifade eder.</span></p>
                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:8.1pt; margin-left:-.25pt;text-align:justify;text-justify:inter-ideograph;text-indent: -.5pt;line-height:107%;"><strong><span style='font-family:"Times New Roman",serif; color:#002060;'>İlgili Kişi:</span></strong> <span style='font-family:"Times New Roman",serif; color:#002060;'>S&ouml;zleşme s&uuml;re&ccedil;lerinde birtakım kişisel verilerini işlediğimiz siz, kanun tarafından ilgili kişi olarak tanımlanmaktasınız.</span></p>
                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:8.1pt; margin-left:-.25pt;text-align:justify;text-justify:inter-ideograph;text-indent: -.5pt;line-height:107%;"><strong><span style='font-family:"Times New Roman",serif; color:#002060;'>Veri Sorumlusu:</span></strong> <span style='font-family:"Times New Roman",serif; color:#002060;'>Sizinle ilgili kişisel veriler konusunda kişisel verilerin işleme ama&ccedil;larını ve vasıtalarını belirleyen, veri kayıt sisteminin kurulmasından ve y&ouml;netilmesinden sorumlu olan <strong>[</strong></span><strong><span style='font-size:10.5pt;line-height:107%;font-family:"Times New Roman",serif; color:#002060;'>PORT NATURE</span></strong><strong><span style='font-family:"Times New Roman",serif; color:#002060;'>]</span></strong> <span style='font-family:"Times New Roman",serif; color:#002060;'>veri sorumlusudur.</span></p>
                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:7.6pt; margin-left:-.25pt;text-indent:-.5pt;"><strong><span style='font-family:"Times New Roman",serif; color:#002060;'>S&uuml;re&ccedil;lere G&ouml;re İşlenen Kişisel Verileriniz, İşlenme Ama&ccedil;ları ve Hukuki Sebepleri</span></strong></p>
                <p class="MsoNormal" style="margin-top:0in;margin-right:524.95pt;margin-bottom: 0in;margin-left:-70.8pt;">&nbsp;</p>
                <table class="TableGrid" border="0" cellspacing="0" cellpadding="0" width="614" style="width:460.4pt;margin-left:.35pt;border-collapse:collapse;">
                    <tbody>
                        <tr style="height:13.1pt;">
                            <td colspan="4" valign="top" style="width: 614px; border: 1pt solid rgb(91, 155, 213); background: rgb(91, 155, 213); padding: 0.3pt 2.6pt 0in 0in; height: 13.1pt;">
                                <p class="MsoNormal" style="margin-bottom:0in;">&nbsp;&nbsp; <strong><span style='font-family: "Times New Roman",serif;color:white;'>İşlenen Kişisel Verileriniz &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; İşlenme Ama&ccedil;ları &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Hukuki Sebepleri</span></strong></p>
                            </td>
                        </tr>
                        <tr style="height:354.35pt;">
                            <td colspan="2" valign="top" style="width: 201px; border-right: 1pt solid rgb(142, 170, 219); border-bottom: 1pt solid rgb(142, 170, 219); border-left: 1pt solid rgb(142, 170, 219); border-image: initial; border-top: none; background: rgb(222, 235, 246); padding: 0.3pt 2.6pt 0in 0in; height: 354.35pt;">
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:1.25pt;"><span style='font-family: "Times New Roman",serif;color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" align="center" style="margin-top:0in;margin-right:0in; margin-bottom:0in;margin-left:19.65pt;text-align:center;text-indent:-.25in;"><span style="line-height:107%;color:#002060;">●<span style='font:7.0pt "Times New Roman";'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span> <span style='font-family:"Times New Roman",serif;color:#002060;'>Kimlik <em>(Ad, Soyad)</em></span></p>
                                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:2.2pt; margin-left:.5in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" align="center" style="margin-top:0in;margin-right:0in; margin-bottom:0in;margin-left:19.65pt;text-align:center;text-indent:-.25in;"><span style="line-height:107%;color:#002060;">●<span style='font:7.0pt "Times New Roman";'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span> <span style='font-family:"Times New Roman",serif;color:#002060;'>Hukuki İşlem <em>(İmza,</em></span></p>
                                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:0in; margin-left:.5in;"><em><span style='font-family:"Times New Roman",serif; color:#002060;'>İmza Tarihi, S&ouml;zleşme</span></em></p>
                                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:0in; margin-left:.5in;"><em><span style='font-family:"Times New Roman",serif; color:#002060;'>Konusu, S&ouml;zleşme</span></em></p>
                                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:0in; margin-left:.5in;"><em><span style='font-family:"Times New Roman",serif; color:#002060;'>İ&ccedil;eriği),</span></em></p>
                                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:2.2pt; margin-left:.5in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" align="center" style="margin-top:0in;margin-right:0in; margin-bottom:0in;margin-left:19.65pt;text-align:center;text-indent:-.25in; line-height:112%;"><span style="line-height:112%;color:#002060;">●<span style='font:7.0pt "Times New Roman";'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span> <span style='font-family:"Times New Roman",serif;color:#002060;'>İletişim <em>(Adresi EPosta)</em> verileriniz.</span></p>
                                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:7.9pt; margin-left:.5in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:0in; margin-left:.5in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                            </td>
                            <td valign="top" style="width: 271px; border-top: none; border-left: none; border-bottom: 1pt solid rgb(142, 170, 219); border-right: 1pt solid rgb(142, 170, 219); background: rgb(222, 235, 246); padding: 0.3pt 2.6pt 0in 0in; height: 354.35pt;">
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>S&ouml;zleşme S&uuml;re&ccedil;lerinin Y&uuml;r&uuml;t&uuml;lmesi</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><em><span style='font-family: "Times New Roman",serif;color:#002060;'>(Tedarik s&ouml;zleşmesinin İmzalanması)</span></em></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>Ama&ccedil;larıyla</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                            </td>
                            <td valign="top" style="width: 142px; border-top: none; border-left: none; border-bottom: 1pt solid rgb(142, 170, 219); border-right: 1pt solid rgb(142, 170, 219); background: rgb(222, 235, 246); padding: 0.3pt 2.6pt 0in 0in; height: 354.35pt;">
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;line-height:98%;"><span style='font-family:"Times New Roman",serif;color:#002060;'>KVKK Md. 5/2(c): Bir s&ouml;zleşmenin kurulması veya ifasıyla doğrudan doğruya ilgili olması kaydıyla,</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>s&ouml;zleşmenin</span></p>
                                <p class="MsoNormal" style="margin-top:0in;margin-right:2.55pt;margin-bottom: 0in;margin-left:0in;line-height:98%;"><span style='font-family:"Times New Roman",serif; color:#002060;'>taraflarına ait kişisel verilerin işlenmesinin gerekli olması bendine</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>istinaden</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><em><span style='font-family: "Times New Roman",serif;color:#002060;'>(S&ouml;zleşmenin kurulabilmesi i&ccedil;in anılan verilerinizi elde etmemiz gerekmektedir.)</span></em></p>
                            </td>
                        </tr>
                        <tr style="height:228.4pt;">
                            <td colspan="2" valign="top" style="width: 201px; border-right: 1pt solid rgb(142, 170, 219); border-bottom: 1pt solid rgb(142, 170, 219); border-left: 1pt solid rgb(142, 170, 219); border-image: initial; border-top: none; padding: 0.3pt 2.6pt 0in 0in; height: 228.4pt;">
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" align="center" style="margin-top:0in;margin-right:0in; margin-bottom:0in;margin-left:19.65pt;text-align:center;text-indent:-.25in;"><span style="line-height:107%;color:#002060;">●<span style='font:7.0pt "Times New Roman";'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span> <span style='font-family:"Times New Roman",serif;color:#002060;'>Kimlik <em>(Ad, Soyad)</em></span></p>
                                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:2.2pt; margin-left:.5in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" align="center" style="margin-top:0in;margin-right:0in; margin-bottom:0in;margin-left:19.65pt;text-align:center;text-indent:-.25in;"><span style="line-height:107%;color:#002060;">●<span style='font:7.0pt "Times New Roman";'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span> <span style='font-family:"Times New Roman",serif;color:#002060;'>Hukuki İşlem <em>(İmza,</em></span></p>
                                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:0in; margin-left:.5in;"><em><span style='font-family:"Times New Roman",serif; color:#002060;'>İmza Tarihi, S&ouml;zleşme</span></em></p>
                                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:1.9pt; margin-left:.5in;"><em><span style='font-family:"Times New Roman",serif; color:#002060;'>Konusu, S&ouml;zleşme</span></em></p>
                                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:0in; margin-left:.5in;"><em><span style='font-family:"Times New Roman",serif; color:#002060;'>İ&ccedil;eriği),</span></em></p>
                                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:1.1pt; margin-left:.5in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" align="center" style="margin-top:0in;margin-right:0in; margin-bottom:0in;margin-left:19.65pt;text-align:center;text-indent:-.25in; line-height:111%;"><span style="line-height:111%;color:#002060;">●<span style='font:7.0pt "Times New Roman";'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span> <span style='font-family:"Times New Roman",serif;color:#002060;'>İletişim <em>(Adresi EPosta)</em> verileriniz.</span></p>
                                <p class="MsoNormal" style="margin-top:0in;margin-right:104.25pt;margin-bottom: 0in;margin-left:.5in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                            </td>
                            <td valign="top" style="width: 271px; border-top: none; border-left: none; border-bottom: 1pt solid rgb(142, 170, 219); border-right: 1pt solid rgb(142, 170, 219); padding: 0.3pt 2.6pt 0in 0in; height: 228.4pt;">
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:.3pt;"><span style='font-family:"Times New Roman",serif; color:#002060;'>Saklama ve Arşiv Faaliyetlerinin</span></p>
                                <p class="MsoNormal" style="margin-bottom:.85pt;"><span style='font-family:"Times New Roman",serif; color:#002060;'>Y&uuml;r&uuml;t&uuml;lmesi <em>(Tedarik s&ouml;zleşmesinin</em></span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><em><span style='font-family: "Times New Roman",serif;color:#002060;'>Saklanması)</span></em> <span style='font-family:"Times New Roman",serif;color:#002060;'>Ama&ccedil;larıyla</span></p>
                            </td>
                            <td valign="top" style="width: 142px; border-top: none; border-left: none; border-bottom: 1pt solid rgb(142, 170, 219); border-right: 1pt solid rgb(142, 170, 219); padding: 0.3pt 2.6pt 0in 0in; height: 228.4pt;">
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>KVKK Md. 5/2(e):</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;line-height:101%;"><span style='font-family:"Times New Roman",serif;color:#002060;'>Bir hakkın tesisi, kullanılması veya korunması i&ccedil;in veri işlemenin zorunlu olması bendine istinaden</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;line-height:99%;"><span style='font-family:"Times New Roman",serif;color:#002060;'>(Olası bir uyuşmazlıkta hakkın koruması i&ccedil;in anılan</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>kişisel verilerinizi saklamamız gerekmektedir.)</span></p>
                            </td>
                        </tr>
                        <tr style="height:101.5pt;">
                            <td colspan="2" valign="top" style="width: 201px; border-right: 1pt solid rgb(142, 170, 219); border-bottom: 1pt solid rgb(142, 170, 219); border-left: 1pt solid rgb(142, 170, 219); border-image: initial; border-top: none; background: rgb(222, 235, 246); padding: 0.3pt 2.6pt 0in 0in; height: 101.5pt;">
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                            </td>
                            <td valign="top" style="width: 271px; border-top: none; border-left: none; border-bottom: 1pt solid rgb(142, 170, 219); border-right: 1pt solid rgb(142, 170, 219); background: rgb(222, 235, 246); padding: 0.3pt 2.6pt 0in 0in; height: 101.5pt;">
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                            </td>
                            <td valign="top" style="width: 142px; border-top: none; border-left: none; border-bottom: 1pt solid rgb(142, 170, 219); border-right: 1pt solid rgb(142, 170, 219); background: rgb(222, 235, 246); padding: 0.3pt 2.6pt 0in 0in; height: 101.5pt;">
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>KVKK Md. 5/2(e):</span></p>
                                <p class="MsoNormal" style="margin-top:0in;margin-right:2.65pt;margin-bottom: 0in;margin-left:0in;text-align:justify;text-justify:inter-ideograph; line-height:99%;"><span style='font-family:"Times New Roman",serif;color:#002060;'>Bir hakkın tesisi, kullanılması veya korunması i&ccedil;in veri işlemenin zorunlu olması bendine</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>istinaden</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                            </td>
                        </tr>
                        <tr style="height:240.7pt;">
                            <td valign="top" style="width: 55px; border-top: none; border-left: 1pt solid rgb(142, 170, 219); border-bottom: 1pt solid rgb(142, 170, 219); border-right: none; background: rgb(222, 235, 246); padding: 0.3pt 2.6pt 0in 0in; height: 240.7pt;">
                                <p class="MsoNormal" align="center" style="margin-top:0in;margin-right:0in; margin-bottom:28.0pt;margin-left:14.8pt;text-align:center;"><span style="color:#002060;">●</span></p>
                                <p class="MsoNormal" align="center" style="margin-top:0in;margin-right:0in; margin-bottom:0in;margin-left:14.8pt;text-align:center;"><span style="color:#002060;">●</span></p>
                            </td>
                            <td valign="top" style="width: 146px; border-top: none; border-left: none; border-bottom: 1pt solid rgb(142, 170, 219); border-right: 1pt solid rgb(142, 170, 219); background: rgb(222, 235, 246); padding: 0.3pt 2.6pt 0in 0in; height: 240.7pt;">
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>Kimlik (Ad, Soyad),</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-top:0in;margin-right:2.65pt;margin-bottom: 0in;margin-left:0in;text-align:justify;text-justify:inter-ideograph; line-height:107%;"><span style='font-family:"Times New Roman",serif; color:#002060;'>Hukuki İşlem (Metnin Ulaştığının beyanı, İmza ve İmza Tarihi) verileriniz</span></p>
                                <p class="MsoNormal" style="margin-top:0in;margin-right:104.1pt;margin-bottom: 0in;margin-left:0in;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                            </td>
                            <td valign="top" style="width: 271px; border-top: none; border-left: none; border-bottom: 1pt solid rgb(142, 170, 219); border-right: 1pt solid rgb(142, 170, 219); background: rgb(222, 235, 246); padding: 0.3pt 2.6pt 0in 0in; height: 240.7pt;">
                                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:0in; margin-left:5.4pt;"><span style='font-family:"Times New Roman",serif; color:#002060;'>Hukuk İşlerinin Takibi ve Y&uuml;r&uuml;t&uuml;lmesi ve</span></p>
                                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:0in; margin-left:5.4pt;"><span style='font-family:"Times New Roman",serif; color:#002060;'>Saklama ve Arşiv Faaliyetlerinin</span></p>
                                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:0in; margin-left:5.4pt;"><span style='font-family:"Times New Roman",serif; color:#002060;'>Y&uuml;r&uuml;t&uuml;lmesi (Bu Aydınlatma Metnini size ulaştırdığımızın ispatı) Amacıyla</span></p>
                            </td>
                            <td valign="top" style="width: 142px; border-top: none; border-left: none; border-bottom: 1pt solid rgb(142, 170, 219); border-right: 1pt solid rgb(142, 170, 219); background: rgb(222, 235, 246); padding: 0.3pt 2.6pt 0in 0in; height: 240.7pt;">
                                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:0in; margin-left:5.4pt;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:0in; margin-left:5.4pt;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:0in; margin-left:5.4pt;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:0in; margin-left:5.4pt;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:0in; margin-left:5.4pt;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:.1pt; margin-left:5.4pt;line-height:98%;"><span style='font-family:"Times New Roman",serif; color:#002060;'>(6698 Sayılı KVKK m.10 gereği aydınlatma</span></p>
                                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:0in; margin-left:5.4pt;"><span style='font-family:"Times New Roman",serif; color:#002060;'>y&uuml;k&uuml;ml&uuml;l&uuml;ğ&uuml;n&uuml;n</span></p>
                                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:0in; margin-left:5.4pt;line-height:99%;"><span style='font-family:"Times New Roman",serif; color:#002060;'>yerine getirildiğinin ispatı veri sorumlusuna aittir.</span></p>
                                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:0in; margin-left:5.4pt;line-height:99%;"><span style='font-family:"Times New Roman",serif; color:#002060;'>Bu nedenle bu metni size ulaştırdığımızın</span></p>
                                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:0in; margin-left:5.4pt;"><span style='font-family:"Times New Roman",serif; color:#002060;'>ispatı, olası bir uyuşmazlıkta hakkımızın korunması i&ccedil;in gereklidir.)</span></p>
                            </td>
                        </tr>
                        <tr>
                            <td style="border: none; width: 55px;"><br></td>
                            <td style="border: none; width: 146px;"><br></td>
                            <td style="border: none; width: 271px;"><br></td>
                            <td style="border: none; width: 142px;"><br></td>
                        </tr>
                    </tbody>
                </table>
                <p class="MsoNormal" style="margin-bottom:7.9pt;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:8.1pt; margin-left:-.25pt;text-align:justify;text-justify:inter-ideograph;text-indent: -.5pt;line-height:107%;"><span style='font-family:"Times New Roman",serif; color:#002060;'>Tarafımızca işlenmektedir.</span></p>
                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:7.6pt; margin-left:-.25pt;text-indent:-.5pt;"><strong><span style='font-family:"Times New Roman",serif; color:#002060;'>Kişisel Verilerin Kimlere ve Hangi Ama&ccedil;la Aktarılabileceği</span></strong></p>
                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:8.1pt; margin-left:-.25pt;text-align:justify;text-justify:inter-ideograph;text-indent: -.5pt;line-height:107%;"><span style='font-family:"Times New Roman",serif; color:#002060;'>Kişisel verileriniz KVKK Md.28/1 &ccedil;er&ccedil;evesinde talep edilmesi halinde aydınlatma y&uuml;k&uuml;ml&uuml;l&uuml;ğ&uuml; olmadan ve a&ccedil;ık rızanız aranmadan ilgili makamlara aktarılabilir.</span></p>
                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:8.1pt; margin-left:-.25pt;text-align:justify;text-justify:inter-ideograph;text-indent: -.5pt;line-height:107%;"><span style='font-family:"Times New Roman",serif; color:#002060;'>Bunun dışında &ouml;ng&ouml;r&uuml;lemeyen durumlarda da kişisel verileriniz kanunlarda a&ccedil;ık&ccedil;a belirtilmiş durumlarda talep edilmesi halinde kanunlarda belirtilen kamu kurumlarına (Bakanlıklar gibi idari makamlara) kanunda &ouml;ng&ouml;r&uuml;len ama&ccedil; ve sınırlamalar dahilinde aktarılabilir.</span></p>
                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:8.1pt; margin-left:-.25pt;text-align:justify;text-justify:inter-ideograph;text-indent: -.5pt;line-height:107%;"><span style='font-family:"Times New Roman",serif; color:#002060;'>Aydınlatma y&uuml;k&uuml;ml&uuml;l&uuml;ğ&uuml; olmayan ve a&ccedil;ık rızanızı gerektirmeyen yasal y&uuml;k&uuml;ml&uuml;l&uuml;klerimizin dışında; kişisel verileriniz aktarılmayacaktır.</span></p>
                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:7.6pt; margin-left:-.25pt;text-indent:-.5pt;"><strong><span style='font-family:"Times New Roman",serif; color:#002060;'>Kişisel Verilerin Elde Edilme Y&ouml;ntemleri</span></strong></p>
                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:8.1pt; margin-left:-.25pt;text-align:justify;text-justify:inter-ideograph;text-indent: -.5pt;line-height:107%;"><span style='font-family:"Times New Roman",serif; color:#002060;'>Kişisel verileriniz s&ouml;zleşmeyi imzalamanız yoluyla otomatik olmayan y&ouml;ntemlerle elde edilmektedir.</span></p>
                <p class="MsoNormal" style="margin-bottom:12.2pt;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                <p class="MsoNormal" style="margin-bottom:0in;"><em><span style='font-size:13.0pt; line-height:107%;font-family:"Times New Roman",serif;color:#002060;'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Kanun uyarınca kişisel verilerinizle ilgili olarak:</span></em></p>
                <table class="TableGrid" border="0" cellspacing="0" cellpadding="0" width="604" style="width:453.2pt;border-collapse:collapse;">
                    <tbody>
                        <tr style="height:15.25pt;">
                            <td valign="top" style="width: 23px; border-top: 1pt solid rgb(160, 43, 147); border-left: none; border-bottom: none; border-right: 1pt solid rgb(160, 43, 147); padding: 0.2pt 2.65pt 0in 5.4pt; height: 15.25pt;">
                                <p class="MsoNormal" style="margin-bottom:0in;"><em><span style='font-size:13.0pt; line-height:107%;font-family:"Times New Roman",serif;color:#002060;'>&nbsp;</span></em></p>
                            </td>
                            <td rowspan="4" valign="top" style="width: 581px; border-right: none; border-bottom: none; border-left: none; border-image: initial; border-top: 1pt solid rgb(160, 43, 147); padding: 0.2pt 2.65pt 0in 5.4pt; height: 15.25pt;">
                                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:3.35pt; margin-left:.1pt;text-align:justify;text-justify:inter-ideograph;text-indent: 0in;"><span style='line-height:107%;font-family:"Times New Roman",serif; color:#002060;'>a)<span style='font:7.0pt "Times New Roman";'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span> <span style='font-family:"Times New Roman",serif;color:#002060;'>Kişisel veri işlenip işlenmediğini &ouml;ğrenme,</span></p>
                                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:1.05pt; margin-left:.1pt;text-align:justify;text-justify:inter-ideograph;text-indent: 0in;"><span style='line-height:107%;font-family:"Times New Roman",serif; color:#002060;'>b)<span style='font:7.0pt "Times New Roman";'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span> <span style='font-family:"Times New Roman",serif;color:#002060;'>Kişisel verileriniz işlenmişse buna ilişkin bilgi talep etme,</span></p>
                                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:.2pt; margin-left:.1pt;text-align:justify;text-justify:inter-ideograph;text-indent: 0in;line-height:114%;"><span style='line-height:114%;font-family:"Times New Roman",serif; color:#002060;'>c)<span style='font:7.0pt "Times New Roman";'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span> <span style='font-family:"Times New Roman",serif;color:#002060;'>Kişisel verilerinizin işlenme amacını ve bunların amacına uygun kullanılıp kullanılmadığını &ouml;ğrenme,</span></p>
                                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:3.25pt; margin-left:.1pt;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&ccedil;) Yurt i&ccedil;inde veya yurt dışında kişisel verilerinizin aktarıldığı &uuml;&ccedil;&uuml;nc&uuml; kişileri bilme,</span></p>
                                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:12.6pt; margin-left:.1pt;text-align:justify;text-justify:inter-ideograph;text-indent: 0in;"><span style='line-height:107%;font-family:"Times New Roman",serif; color:#002060;'>d)<span style='font:7.0pt "Times New Roman";'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span> <span style='font-family:"Times New Roman",serif;color:#002060;'>Kişisel verilerinizin eksik veya yanlış işlenmiş olması h&acirc;linde bunların d&uuml;zeltilmesini isteme,</span></p>
                                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:0in; margin-left:.1pt;text-align:justify;text-justify:inter-ideograph;text-indent: 0in;line-height:98%;"><span style='line-height:98%;font-family:"Times New Roman",serif; color:#002060;'>e)<span style='font:7.0pt "Times New Roman";'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span> <span style='font-family:"Times New Roman",serif;color:#002060;'>İşlenmesini gerektiren sebeplerin ortadan kalkması h&acirc;linde kişisel verilerinizin silinmesini veya yok edilmesini isteme,</span></p>
                                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:0in; margin-left:.1pt;text-align:justify;text-justify:inter-ideograph;text-indent: 0in;line-height:99%;"><span style='line-height:99%;font-family:"Times New Roman",serif; color:#002060;'>f)<span style='font:7.0pt "Times New Roman";'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span> <span style='font-family:"Times New Roman",serif;color:#002060;'>(d) ve (e) bentleri uyarınca yapılan işlemlerin, kişisel verilerinizin aktarıldığı &uuml;&ccedil;&uuml;nc&uuml; kişilere bildirilmesini isteme,</span></p>
                                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:0in; margin-left:.1pt;text-align:justify;text-justify:inter-ideograph;text-indent: 0in;"><span style='line-height:107%;font-family:"Times New Roman",serif; color:#002060;'>g)<span style='font:7.0pt "Times New Roman";'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span> <span style='font-family:"Times New Roman",serif;color:#002060;'>İşlenen verilerinizin m&uuml;nhasıran otomatik sistemler vasıtasıyla analiz edilmesi suretiyle aleyhinize bir sonucun ortaya &ccedil;ıkmasına itiraz etme,</span></p>
                            </td>
                        </tr>
                        <tr style="height:14.9pt;">
                            <td valign="top" style="width: 23px; border-top: none; border-bottom: none; border-left: none; border-image: initial; border-right: 1pt solid rgb(160, 43, 147); background: white; padding: 0.2pt 2.65pt 0in 5.4pt; height: 14.9pt;">
                                <p class="MsoNormal" style="margin-bottom:0in;"><em><span style='font-size:13.0pt; line-height:107%;font-family:"Times New Roman",serif;color:#002060;'>&nbsp;</span></em></p>
                            </td>
                        </tr>
                        <tr style="height:25.35pt;">
                            <td valign="top" style="width: 23px; border-top: none; border-bottom: none; border-left: none; border-image: initial; border-right: 1pt solid rgb(160, 43, 147); padding: 0.2pt 2.65pt 0in 5.4pt; height: 25.35pt;">
                                <p class="MsoNormal" style="margin-bottom:0in;"><em><span style='font-size:13.0pt; line-height:107%;font-family:"Times New Roman",serif;color:#002060;'>&nbsp;</span></em></p>
                            </td>
                        </tr>
                        <tr style="height:117.1pt;">
                            <td valign="top" style="width: 23px; border-top: none; border-bottom: none; border-left: none; border-image: initial; border-right: 1pt solid rgb(160, 43, 147); background: white; padding: 0.2pt 2.65pt 0in 5.4pt; height: 117.1pt;">
                                <p class="MsoNormal" style="margin-bottom:0in;"><em><span style='font-size:13.0pt; line-height:107%;font-family:"Times New Roman",serif;color:#002060;'>&nbsp;</span></em></p>
                                <p class="MsoNormal" style="margin-bottom:10.05pt;"><em><span style='font-size: 13.0pt;line-height:107%;font-family:"Times New Roman",serif;color:#002060;'>&nbsp;</span></em></p>
                                <p class="MsoNormal" style="margin-bottom:9.1pt;"><em><span style='font-size: 13.0pt;line-height:107%;font-family:"Times New Roman",serif;color:#002060;'>&nbsp;</span></em></p>
                                <p class="MsoNormal" style="margin-bottom:9.1pt;"><em><span style='font-size: 13.0pt;line-height:107%;font-family:"Times New Roman",serif;color:#002060;'>&nbsp;</span></em></p>
                                <p class="MsoNormal" style="margin-bottom:0in;"><em><span style='font-size:13.0pt; line-height:107%;font-family:"Times New Roman",serif;color:#002060;'>&nbsp;</span></em></p>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:.5pt; margin-left:23.05pt;text-align:justify;text-justify:inter-ideograph;text-indent: -17.65pt;line-height:112%;"><img width="1" height="34" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAAiAQMAAACk4yFSAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAADUExURaArk2F0Xy0AAAAJcEhZcwAADsMAAA7DAcdvqGQAAAANSURBVBjTY6AYMDAAAABEAAHdnSV1AAAAAElFTkSuQmCC" alt="image" style="float: left; "><em><span style='font-size:13.0pt;line-height:112%; font-family:"Times New Roman",serif;color:#002060;'>&nbsp;</span></em><span style='font-family:"Times New Roman",serif;color:#002060;'>ğ) Kişisel verilerin kanuna aykırı olarak işlenmesi sebebiyle zarara uğramanız h&acirc;linde zararın giderilmesini talep etme haklarını kullanabilirsiniz.</span></p>
                <p class="MsoNormal" style="margin-bottom:10.45pt;"><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp;</span></p>
                <p class="MsoNormal" style="margin-top:0in;margin-right:307.4pt;margin-bottom: .7pt;margin-left:0in;line-height:183%;"><strong><span style='font-family:"Times New Roman",serif; color:#002060;'>Başvuru Y&ouml;ntemi</span></strong> <span style='font-family:"Times New Roman",serif; color:#002060;'>Başvurunuzu:&nbsp;</span></p>
                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:1.5pt; margin-left:18.5pt;text-align:justify;text-justify:inter-ideograph;text-indent: -.5pt;line-height:112%;"><span style="color:#002060;">▪</span> <span style='font-family:"Arial",sans-serif;color:#002060;'>&nbsp;&nbsp;&nbsp;</span> <span style='font-family:"Times New Roman",serif;color:#002060;'>Fener Mah. 1962.Sk. Aras Sitesi C Blok 2CB Muratpaşa/ ANTALYA adresine yazılı olarak;</span> <span style="color:#002060;">▪</span> <span style='font-family:"Arial",sans-serif; color:#002060;'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <u><span style='font-family:"Times New Roman",serif; color:#0563C1;'>aras.insaat@hs.kep.tr</span></u> <span style='font-family:"Times New Roman",serif; color:#002060;'>kep adresine g&uuml;venli elektronik imza veya mobil imza ile;</span></p>
                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:9.35pt; margin-left:.5in;text-align:justify;text-justify:inter-ideograph;text-indent: -.25in;line-height:112%;"><span style="color:#002060;">▪</span> <span style='font-family:"Times New Roman",serif;color:#002060;'>Elektronik posta adresinizin sistemimizde kayıtlı olması halinde aynı e-posta adresini kullanarak</span> <u><span style='font-family:"Times New Roman",serif; color:#0563C1;'>kvkk@portnature.com.tr</span></u><span style='font-family:"Times New Roman",serif; color:#002060;'>&nbsp; adresimize e-posta g&ouml;ndererek yapabilirsiniz.</span></p>
                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:9.95pt; margin-left:-.25pt;text-align:justify;text-justify:inter-ideograph;text-indent: -.5pt;line-height:112%;"><span style='font-family:"Times New Roman",serif; color:#002060;'>Başvurunuzda;</span></p>
                <p class="MsoNormal" style="margin-bottom:1.5pt;line-height:112%;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color:#002060;">▪</span> <span style='font-family:"Arial",sans-serif; color:#002060;'>&nbsp;&nbsp;</span> <span style='font-family:"Times New Roman",serif; color:#002060;'>Adınızın, soyadınızın ve başvuru yazılı ise imzanızın,</span></p>
                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:1.5pt; margin-left:.5in;text-align:justify;text-justify:inter-ideograph;text-indent: -.25in;line-height:112%;"><span style="color:#002060;">▪</span> <span style='font-family:"Times New Roman",serif;color:#002060;'>T&uuml;rkiye Cumhuriyeti vatandaşları i&ccedil;in T.C. kimlik numaranızın, yabancı iseniz uyruğunuzun, pasaport numaranızın veya varsa kimlik numaranızın,</span></p>
                <p class="MsoNormal" style="margin-bottom:1.5pt;line-height:112%;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color:#002060;">▪</span> <span style='font-family:"Arial",sans-serif; color:#002060;'>&nbsp;&nbsp;&nbsp;</span> <span style='font-family:"Times New Roman",serif; color:#002060;'>Tebligata esas yerleşim yeri veya iş yeri adresinizin,</span></p>
                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:4.15pt; margin-left:-.75pt;text-align:justify;text-justify:inter-ideograph;text-indent: .25in;line-height:149%;"><span style="color:#002060;">▪</span> <span style='font-family:"Times New Roman",serif;color:#002060;'>Varsa bildirime esas elektronik posta adresi, telefon ve faks numaranızın,</span> <span style="color:#002060;">▪</span> <span style='font-family:"Times New Roman",serif; color:#002060;'>Talep konunuzun, bulunması zorunlu olup varsa konuya ilişkin bilgi ve belgelerin de başvuruya eklenmesi gerekmektedir.</span></p>
                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:7.4pt; margin-left:-.25pt;text-align:justify;text-justify:inter-ideograph;text-indent: -.5pt;line-height:112%;"><strong><span style='font-family:"Times New Roman",serif; color:#002060;'>PORT NATURE</span></strong><span style='font-family:"Times New Roman",serif; color:#002060;'>, kimliğinizi doğrulama hakkını saklı tutar.</span></p>
                <p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:7.45pt; margin-left:-.25pt;text-align:justify;text-justify:inter-ideograph;text-indent: -.5pt;line-height:112%;"><span style='font-family:"Times New Roman",serif; color:#002060;'>Başvuru sırasında uyulması gereken usul kuralları ve daha detaylı bilgiye Kişisel Verileri Koruma Kurumu&apos;nun &quot;</span><a href="http://www.resmigazete.gov.tr/eskiler/2018/03/20180310-6.htm"><span style='font-family:"Times New Roman",serif;color:#002060;'>Veri Sorumlusuna Başvuru Usul ve Esasları Hakkında Tebliğ</span></a><a href="http://www.resmigazete.gov.tr/eskiler/2018/03/20180310-6.htm"><span style='font-family:"Times New Roman",serif;color:#002060;text-decoration:none;'>&quot;</span></a><span style='font-family:"Times New Roman",serif;color:#002060;'>inden ulaşabilirsiniz.</span></p>
                <p class="MsoNormal" style="margin-bottom:8.05pt;">&nbsp;</p>
                <p class="MsoNormal" align="right" style="margin-top:0in;margin-right:30.95pt; margin-bottom:7.9pt;margin-left:.5pt;text-align:right;text-indent:-.5pt;">Aydınlatma Metnini Okudum, Anladım.</p>
                <p class="MsoNormal" align="center" style="margin-left:44.1pt;text-align:center;">&nbsp;</p>
                <p class="MsoNormal" align="center" style="margin-top:0in;margin-right:0in; margin-bottom:7.9pt;margin-left:44.1pt;text-align:center;">&nbsp;</p>
                <p class="MsoNormal" align="right" style="margin-top:0in;margin-right:40.2pt; margin-bottom:7.9pt;margin-left:.5pt;text-align:right;text-indent:-.5pt;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ad-Soyad&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Tarih:&nbsp;&nbsp;&nbsp; /&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; /&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
            </div>
           
        </div>
        <div class="text-center">
            <img src="{{ asset('assets/frontend/images/contact/urun-hizmet-aydinlatma.png ') }}" width="240" height="240">
        </div>
    </div>
</div>
@endsection

@section('javascript-imports')
@endsection

@section('css-imports')
<link rel="stylesheet" href="{{ asset('assets/frontend/css/data-policy.css') }}"/>
@endsection